FROM node:18.16-alpine

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install --production

COPY ./dist ./dist

# Start the server using the production build
CMD [ "node", "dist/apps/server/main.js" ]